apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-test.fullname" . }}
spec:
  selector:
    {{- include "k8s-test.selectorLabels" . | nindent 4}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}