apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
data:
  config.yml: |
    server:
      http_listen_port: 9080
    clients: 
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: 'k8s-test'
        static_configs:
          - labels:
              __path__: /var/lib/docker/containers/*/*-json.log
      - job_name: 'loki'
        static_configs:
          - labels:
              __path__: /var/log/pods/*/*/*.log